upstream cluster {
    server shop-app-php1:9000;
    server shop-app-php2:9000;
    server shop-app-php3:9000;
}

server {
  listen 80;
  server_name ~^(?<subdomain>.+)\.localhost$;
  root /app/public;
  index index.php index.htm index.html;
  client_max_body_size 10M;

  location / {
      try_files $uri $uri/ /index.php?$query_string;
  }

  location /index.php {
      include fastcgi_params;
      fastcgi_connect_timeout 100s;
      fastcgi_read_timeout 100s;
      fastcgi_buffers 256 4k;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param SUBDOMAIN $subdomain; # $_SERVER['SUBDOMAIN']
      fastcgi_pass cluster;
  }

  location ~* \.(js|css|png|svg|jpg)$ {
          add_header Access-Control-Allow-Origin *;
  }
}

server {
    listen 443;
    server_name shop-app.example.com;
    root /app/public;

    ssl_certificate /etc/nginx/server.crt;
    ssl_certificate_key /etc/nginx/server.key;

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;
    client_max_body_size 10M;

    location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

  location /index.php {
      include fastcgi_params;
      fastcgi_connect_timeout 10s;
      fastcgi_read_timeout 10s;
      fastcgi_buffers 256 4k;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_pass cluster;
  }

  location ~* \.(js|css|png|svg|jpg)$ {
      add_header Access-Control-Allow-Origin *;
  }
}
