{{- if .Values.kafka.enabled }}
{{- $vaultSecret := lookup "v1" "Secret" "kafka" "kafka-vault-credentials" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kafka-jaas
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $vaultSecret }}
  client-passwords: {{ $vaultSecret.data.kafkaClientPassword | quote }}
  inter-broker-password: {{ $vaultSecret.data.kafkaInterBrokerPassword | quote }}
  {{- else }}
  client-passwords: {{ "VAULT_KAFKA_CLIENT_PASSWORD" | b64enc | quote }}
  inter-broker-password: {{ "VAULT_KAFKA_INTER_BROKER_PASSWORD" | b64enc | quote }}
  {{- end }}
{{- end }}
