---
- name: Перезапустить docker compose приложения
  community.docker.docker_compose_v2:
    project_src: "{{ docker_app_base_dir }}/{{ docker_app.slug }}"
    env_files: "{{ docker_app_compose_env_files if docker_app_compose_env_files | length > 0 else omit }}"
    state: present
    pull: "{{ docker_app_compose_pull }}"
    recreate: "{{ docker_app_compose_recreate | default('always') }}"
  listen: restart docker app compose
