services:
  ovpn-admin:
    image: ovpn-admin:local
    container_name: ovpn-admin
    command: ["/app/ovpn-admin"]
    ports:
      - "8080:8080"
    volumes:
      - /etc/openvpn/easy-rsa:/etc/openvpn/easyrsa
      - /etc/openvpn/ccd:/etc/openvpn/ccd
      - /etc/openvpn/tc.key:/etc/openvpn/tc.key:ro
      - /etc/openvpn/easy-rsa/pki/ta.key:/etc/openvpn/easyrsa/pki/ta.key:ro
      - ./templates:/app/templates
    environment:
      - OVPN_ROLE=master
      - OVPN_MASTER_HOST=http://127.0.0.1
      - OVPN_MASTER_USER=admin
      - OVPN_MASTER_PASSWORD=CHANGE_ME
      - OVPN_DEBUG=true
      - OVPN_VERBOSE=true
      - OVPN_AUTH_DB_INIT=true
      - OVPN_AUTH_DB_PATH=/etc/openvpn/easyrsa/pki/users.db
      - LOG_LEVEL=debug
      - OVPN_LISTEN_HOST=0.0.0.0
      - OVPN_LISTEN_PORT=8080
      - OVPN_NETWORK=10.8.0.0/24
      - OVPN_SERVER=203.0.113.10:1194:udp
      - EASYRSA_PATH=/etc/openvpn/easyrsa
      - OVPN_INDEX_PATH=/etc/openvpn/easyrsa/pki/index.txt
      - OVPN_CCD=true
      - OVPN_CCD_PATH=/etc/openvpn/ccd
      - OVPN_TLS_AUTH_PATH=/etc/openvpn/easyrsa/pki/ta.key
      - OVPN_TEMPLATES_CC_PATH=/app/templates/client.conf.tpl
      - OVPN_TEMPLATES_CCD_PATH=/app/templates/ccd.tpl
      - OVPN_METRICS_PATH=/metrics
    restart: unless-stopped
    network_mode: host
