apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: estate-keycloak-vault-secrets
  namespace: estate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: estate-keycloak-vault-secrets
    creationPolicy: Owner
  data:
  - secretKey: KC_DB_PASSWORD
    remoteRef:
      key: secret/estate-keycloak
      property: KC_DB_PASSWORD
  - secretKey: KEYCLOAK_ADMIN_PASSWORD
    remoteRef:
      key: secret/estate-keycloak
      property: KEYCLOAK_ADMIN_PASSWORD
