[project]
name = "edr-coverage"
version = "0.7.2"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "huaweicloudsdkcore>=3.1.186",
    "huaweicloudsdkecs>=3.1.196",
    "huaweicloudsdkiam>=3.1.186",
    "pandas>=3.0.3",
    "pandas-stubs==3.0.0.260204",
    "ldap3>=2.9.1",
    "prometheus-client>=0.25.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "pytest>=8.3.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
