apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  labels: {{- include "labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "labels" . | nindent 8 }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- if or .Values.podAnnotations .Values.metrics.enabled }}
        {{- include "podAnnotations" . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      containers:
      - name: {{ include "name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- if .Values.args }}
        args:
        {{- range $key, $value := .Values.args }}
          {{- if $value }}
        - {{ $key }}={{ $value }}
          {{- else }}
        - {{ $key }}
          {{- end }}
        {{- end }}
        {{- end }}
        args: ["start", "--db","postgres","--hostname-strict-https","false","--hostname-strict","false","--proxy","edge","--http-enabled","true","--import-realm","--spi-user-profile-legacy-user-profile-read-only-attributes","*_RES_ACCESS_MODE"]
        {{- if or .Values.env .Values.extraEnv }}
        env:
        {{- if .Values.env }}
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}

        {{- if .Values.extraEnv }}
          {{- toYaml .Values.extraEnv | nindent 8 }}
        {{- end }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        {{- if .Values.readinessProbe }}
        readinessProbe: {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.livenessProbe }}
        livenessProbe: {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.securityContext }}
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 8 }}
        {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 6 }}
      {{- end }}
