---

- name: Install hvac if needed
  ansible.builtin.pip:
    name: hvac 
    state: present

- name: Initialize password dictionary
  set_fact:
    db_passwords: {}

- name: Process db list (if set)
  include_tasks: process_user.yml 
  loop: "{{ db | default([]) }}"
  loop_control:
    loop_var: user_item

- name: Process db_users list (if set)
  include_tasks: process_user.yml
  loop: "{{ db_users | default([]) }}"
  loop_control:
    loop_var: user_item
