---

- name: Установить hvac при необходимости
  ansible.builtin.pip:
    name: hvac 
    state: present

- name: Инициализация словаря паролей
  set_fact:
    db_passwords: {}

- name: Обработка списка из db (если задан)
  include_tasks: process_user.yml 
  loop: "{{ db | default([]) }}"
  loop_control:
    loop_var: user_item

- name: Обработка списка из db_users (если задан)
  include_tasks: process_user.yml
  loop: "{{ db_users | default([]) }}"
  loop_control:
    loop_var: user_item
