[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor
nodaemon=true

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:test-queue-consumer]
command=php /app/bin/cli.php app:amqp:consume test-command-queue
directory=/app
autostart=true
autorestart=true
startretries=3
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/test-consumer.log
stderr_logfile=/var/log/supervisor/test-consumer-error.log

[program:print-queue-consumer]
command=php /app/bin/cli.php printing:consume
directory=/app
autostart=true
autorestart=true
startretries=3
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/print-consumer.log
stderr_logfile=/var/log/supervisor/print-consumer-error.log

