services:
  Jira:
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"
    container_name: Jira
    restart: unless-stopped
    image: atlassian/jira-software:9.15.2
    environment:
      - TZ=Europe/Moscow
      - ATL_PROXY_NAME=jira.example.com
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
    volumes:
#      - /docker/SSL_certs/smtp.example.com/wildcert.pem:/tmp/smtp-example.crt:ro
      - ./Volumes/setenv.sh:/opt/atlassian/jira/bin/setenv.sh:ro
      - ./Volumes/agent:/var/agent/
      - ./Volumes/app_data/jira:/var/atlassian/application-data/jira
     # - /etc/ssl/certs/:/etc/ssl/certs/:ro
      - ./Volumes/cacerts:/opt/java/openjdk/lib/security/cacerts:ro
     # - ./for_ldaps_java_jiraSD:/opt/java/openjdk/lib/security/
    networks:
      - "frontend"
    dns:
      - '10.10.1.9'
    ports:
      - 8082:8080
networks:
  frontend:
    name: frontend
    external: true
