security.protocol=SSL
ssl.endpoint.identification.algorithm=https
ssl.keystore.location=/certs/{{ kafka_host_id }}.pem
ssl.keystore.type=PEM
ssl.truststore.location=/certs/ca.crt
ssl.truststore.type=PEM
