upstream git {
   server gitlab:80;
}

server {
    listen       80;
    server_name  *.pages-dev.example.com;
    location / {
        proxy_pass http://git;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
    }
}

server {
    listen       80;
    server_name  git-dev.example.com;
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    server_name git-dev.example.com;
    listen 443 ssl;
    ssl_certificate         /etc/nginx/ssl/tls.crt;
    ssl_certificate_key     /etc/nginx/ssl/tls.key;

    location / {
        proxy_pass http://git;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        client_max_body_size       40960m;
    }
}
