---
# Node Exporter: Docker Compose в /docker/apps/node-exporter
node_exporter_base_dir: /docker/apps/node-exporter
node_exporter_image: quay.io/prometheus/node-exporter:latest
node_exporter_container_name: node-exporter
node_exporter_compose_pull: always
node_exporter_metrics_port: 9100

node_exporter_command:
  - "--path.rootfs=/host"
  - "--path.procfs=/host/proc"
  - "--collector.processes"
  - "--collector.pressure"
  - "--collector.interrupts"
  - "--collector.softirqs"
  - "--collector.tcpstat"
  - "--collector.systemd"
