project: backup
configVersion: 1
---
image: backup
from: ubuntu:20.04
git:
- add: '/'
  to: '/app'
  stageDependencies:
    install:
    - '.helm/vars/vars'
    setup:
    - '00-scripts'
shell:
  install:
  - apt-get update
  - DEBIAN_FRONTEND="noninteractive" TZ="UTC" apt-get install openssh-client wget tzdata apt-transport-https software-properties-common iputils-ping bind9-host telnet vim curl screen unzip openssl ca-certificates -y
  - wget -q https://github.com/borgbackup/borg/releases/download/1.1.17/borg-linux64 -O /usr/bin/borg && chmod +x /usr/bin/borg
  - ln -sf /usr/bin/borg /usr/bin/borgfs
  - wget -q https://github.com/aptible/supercronic/releases/download/v0.2.1/supercronic-linux-amd64 -O /usr/local/bin/supercronic && chmod +x /usr/local/bin/supercronic
  - wget -q https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_x86_64 -O /usr/local/bin/dumb-init  && chmod +x /usr/local/bin/dumb-init
  - wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | tee /etc/apt/sources.list.d/postgresql-pgdg.list > /dev/null
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add - && echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
  - apt update && apt-get install postgresql-client-14 mongodb-org mysql-client -y
  - wget https://releases.hashicorp.com/vault/1.17.3/vault_1.17.3_linux_amd64.zip && unzip vault_1.17.3_linux_amd64.zip && mv vault /usr/bin/vault && chmod 0755 /usr/bin/vault
  - ln -sf /usr/share/zoneinfo/UTC /etc/localtime
  setup:
  - command -v backup_notify >/dev/null || echo "backup_notify not on PATH (optional alerting CLI)"
  - chmod +x /app/00-scripts -R
  - touch /app/UNDER_KUBERNETES