---
- name: Run deploy all ig
  hosts: swarm_manager
  gather_facts: true

  roles:
    - role: network
      tags: ["network"]

### Задача для вызова роли
  tasks:
      ### Вызов роли для деплоя Redis
    - name: Deploy redis
      ansible.builtin.include_role:
        name: redis
      when:
        - "{{ (ig_caching_provider | string | lower) == 'redis' }}"
    ### Вызов роли для деплоя IG
    - name: Deploy ig
      ansible.builtin.include_role:
        name: ig
    ### Вызов роли для деплоя IgExt
    - name: Deploy IG EXT
      ansible.builtin.include_role:
        name: igext
      when:
        - "{{ ig_enable_ReverseAccess | bool }}"

