---
- name: Run deploy all ig
  hosts: swarm_manager
  gather_facts: true

  roles:
    - role: network
      tags: ["network"]

### Task to include the role
  tasks:
      ### Include the Redis deploy role
    - name: Deploy redis
      ansible.builtin.include_role:
        name: redis
      when:
        - "{{ (ig_caching_provider | string | lower) == 'redis' }}"
    ### Include the IG deploy role
    - name: Deploy ig
      ansible.builtin.include_role:
        name: ig
    ### Include the IgExt deploy role
    - name: Deploy IG EXT
      ansible.builtin.include_role:
        name: igext
      when:
        - "{{ ig_enable_ReverseAccess | bool }}"

