node.id=0
broker.rack=broker-rack-0
process.roles=controller,broker

advertised.listeners=INTERNAL://10.10.9.11:9091,CLIENT://10.10.9.11:9092,EXTERNAL://10.10.9.11:9094,EIP://kafka-eip-0001.example.com:9093
listeners=INTERNAL://:9091,CLIENT://:9092,EXTERNAL://:9094,EIP://:9093
listener.security.protocol.map=INTERNAL:SSL,CLIENT:SASL_SSL,EXTERNAL:SSL,EIP:SSL

inter.broker.listener.name=EXTERNAL
#security.inter.broker.protocol=SSL
sasl.enabled.mechanisms=SCRAM-SHA-512
listener.name.client.scram-sha-512.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required;
controller.quorum.voters=0@10.10.9.11:9091,1@10.10.9.12:9091,2@10.10.9.13:9091
controller.listener.names=INTERNAL

ssl.client.auth=required
ssl.keystore.type=PEM
ssl.truststore.type=PEM

listener.name.internal.ssl.keystore.location=/certs/0.pem
listener.name.internal.ssl.truststore.location=/certs/ca.crt
listener.name.client.ssl.keystore.location=/certs/0.pem
listener.name.client.ssl.truststore.location=/certs/ca.crt
listener.name.external.ssl.keystore.location=/certs/0.pem
listener.name.external.ssl.truststore.location=/certs/ca.crt
listener.name.eip.ssl.keystore.location=/certs/eip.pem
listener.name.eip.ssl.truststore.location=/certs/ca.crt

ssl.endpoint.identification.algorithm=https
ssl.protocol=TLS
ssl.enabled.protocols=TLSv1.2,TLSv1.3

authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
super.users=User:CN=cluster-admin;User:CN=kafka-broker-0001;User:CN=kafka-broker-0002;User:CN=kafka-broker-0003
allow.everyone.if.no.acl.found=false

auto.create.topics.enable=false
default.replication.factor=1
delete.topic.enable=true
group.initial.rebalance.delay.ms=0
log.dirs=/var/lib/kafka/data
log.flush.interval.messages=10000
log.flush.interval.ms=1000
log.retention.bytes=1073741824
log.retention.check.interval.ms=300000
log.retention.check.intervals.ms=300000
log.retention.hours=168
log.segment.bytes=1073741824
max.partition.fetch.bytes=1048576
max.request.size=100000012
message.max.bytes=100000012
num.io.threads=8
num.network.threads=3
num.partitions=1
num.recovery.threads.per.data.dir=1
offsets.retention.minutes=4320
offsets.topic.replication.factor=1
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
socket.send.buffer.bytes=102400
transaction.state.log.min.isr=1
transaction.state.log.replication.factor=1
min.insync.replicas=2
