user nginx;
error_log /dev/stdout;
events {
  worker_connections 1024;
}
http {
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  server_tokens off;
  set_real_ip_from 0.0.0.0/0;
  real_ip_header X-Forwarded-For;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  large_client_header_buffers 4 256k;

  log_format combined_plus escape=json
    '{'
      '"time": "$time_iso8601",'
      '"request_id": "$request_id",'
      '"remote_addr": "$remote_addr", '
      '"remote_user": "$remote_user", '
      '"bytes_received": $request_length,'
      '"bytes_sent": $bytes_sent,'
      '"protocol": "$server_protocol",'
      '"scheme": "$scheme",'
      '"method": "$request_method",'
      '"host": "$host",'
      '"request_uri": "$request_uri",'
      '"request_query": "$args",'
      '"referrer": "$http_referer",'
      '"user_agent": "$http_user_agent",'
      '"request_time": $request_time,'
      '"status": $status,'
      '"vhost": "$server_name",'
      '"nginx_upstream_addr": "$upstream_addr",'
      '"nginx_upstream_bytes_received": "$upstream_bytes_received",'
      '"nginx_upstream_response_time": "$upstream_response_time",'
      '"nginx_upstream_status": "$upstream_status"'
    '}';
  server {
    listen 8080 default_server;
    listen 80 default_server;
    server_name _;
    charset utf-8;
    client_max_body_size 128M;
    access_log  /dev/stdout combined_plus;

    gzip on;
    gzip_static on;
    gzip_vary on;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;

    location ~* ^.+\.(png|jpg|jpeg|gif|svg|js|mp3|ogg|mpe?g|avi|zip|gz|bz2?|rar|swf|ico|css)$ {
      root /app;
      gzip_vary on;
      expires 30d;
      etag on;
    }

    location / {
      index index.php;
      root /app;
      if (!-e $request_filename ) {
        rewrite ^(.*)$ /index.php?q=$1;
      }
    }

    location = /basic_status {
      stub_status;
    }

    location = /status {
      access_log off;
      allow 127.0.0.1;
      allow 172.20.0.0/16;
      allow 172.17.0.0/16;
      deny all;
      fastcgi_pass php_oms:9000;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      include fastcgi_params;
      fastcgi_param REMOTE_ADDR $remote_addr;
    }

    location = /favicon.ico {
      root /app;
      log_not_found off;
    }

    location ~ \.php$ {
      root /app;
      fastcgi_pass php_oms:9000;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      include fastcgi_params;
      fastcgi_param REMOTE_ADDR $remote_addr;
    }
  }
}
