{
 "title": "Kubernetes / System / CoreDNS",
 "description": "This is a modern CoreDNS dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "CCE",
  "Kubernetes",
  "SberCloud"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": "default" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(coredns_dns_requests_total{cluster=\"$cluster\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\"},service)"
    }
   },
   {
    "name": "resolution",
    "query": "1s, 10s, 15s, 20s, 30s, 1m, 3m, 5m"
   },
   { "name": "job", "query": "kubernetes-service-endpoints" }
  ]
 },
 "panels": [
  {
   "title": "CoreDNS - Health Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\", service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "CoreDNS - CPU Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Memory Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Total DNS Requests (udp + tcp)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (proto)",
     "legendFormat": "total {{ proto }} requests"
    }
   ]
  },
  {
   "title": "CoreDNS - Average Packet Size (udp + tcp)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_size_bytes_sum{service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (proto) / sum(rate(coredns_dns_request_size_bytes_count{service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (proto)",
     "legendFormat": "average {{ proto }} packet size"
    }
   ]
  },
  {
   "title": "CoreDNS - Requests by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Requests by return code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (rcode)",
     "legendFormat": "{{ rcode }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Total Forward Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{proxy_name=\"forward\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "total forward requests"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{proxy_name=\"forward\", rcode=~\"SERVFAIL|REFUSED\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (rcode)",
     "legendFormat": "{{ rcode }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Cache Hits / Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (type)",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "CoreDNS - Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\", job=~\"$job\"}) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS request duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_request_duration_seconds_bucket{service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", cluster=\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS request size",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_request_size_bytes_bucket{service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", le!=\"0\", cluster=\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS response size",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_response_size_bytes_bucket{service=~\"$instance\", service!=\"ingress-nginx-controller-metrics\", service!~\"node-exporter.*\", le!=\"0\", cluster=\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}