server {
    error_log  /var/log/nginx/error-aggregate.log warn;
    error_log  /var/log/nginx/keycloak.example.com/error.log  warn;
    access_log /var/log/nginx/access-aggregate.log wallarm;
    access_log /var/log/nginx/keycloak.example.com/access.log wallarm;
    access_log /dev/stdout wallarm;
    access_log /var/log/nginx/keycloak.example.com/wallarm-security.log wallarm if=$wallarm_attack_type_list;
    server_name keycloak.example.com;
    listen 80;

    return 301 https://keycloak.example.com;

}

server {
    error_log  /var/log/nginx/error-aggregate.log warn;
    error_log  /var/log/nginx/keycloak.example.com/error.log  warn;
    access_log /var/log/nginx/access-aggregate.log wallarm;
    access_log /var/log/nginx/keycloak.example.com/access.log wallarm;
    access_log /dev/stdout wallarm;
    access_log /var/log/nginx/keycloak.example.com/wallarm-security.log wallarm if=$wallarm_attack_type_list;
    server_name keycloak.example.com;
    listen 443 ssl;
    ssl_certificate /docker/certgen/data/example.com.crt;
    ssl_certificate_key /docker/certgen/data/example.com.key;

    include /etc/nginx/conf_add/wallarm-blocked-page;
    client_max_body_size 100m;
 
    location / {
        proxy_pass https://k8s-ift;
        proxy_ssl_server_name on;
        proxy_ssl_name $host;
        proxy_set_header Host keycloak.example.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header x-ms-proxy $server_name;
	#ws
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";	
    }
}
