apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: nifi
        image: apache/nifi:2.6.0
        resources:
          requests: {cpu: 1000m, memory: 2048Mi}
          limits: {cpu: 2000m, memory: 4096Mi}
        env:
        - name: SINGLE_USER_CREDENTIALS_USERNAME
          value: "{{ .Values.user }}"
        - name: SINGLE_USER_CREDENTIALS_PASSWORD
          value: "{{ .Values.pass }}"
        - name: NIFI_WEB_PROXY_HOST
          value: "{{ .Values.domain }}"
        ports:
        - name: https
          containerPort: 8443
          protocol: TCP
        volumeMounts:
        - name: nifi
          mountPath: /opt/nifi/nifi-current/flowfile_repository
          subPath: flowfile_repository
        - name: nifi
          mountPath: /opt/nifi/nifi-current/content_repository
          subPath: content_repository
        - name: nifi
          mountPath: /opt/nifi/nifi-current/provenance_repository
          subPath: provenance_repository
        - name: nifi
          mountPath: /opt/nifi/nifi-current/database_repository
          subPath: database_repository
        - name: nifi
          mountPath: /opt/nifi/nifi-current/state/local
          subPath: state
      volumes:
        - name: nifi
          persistentVolumeClaim:
            claimName: nifi
