kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nifi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume_size }}
  storageClassName: example-block
