services:
  shop-app-mysql:
      image: arm64v8/mysql:oracle
      container_name: shop-app-mysql
      ports:
        - "1002:3306"
      command: >
              --default-authentication-plugin=mysql_native_password
              --secure-file-priv=NULL
      environment:
        MYSQL_ROOT_PASSWORD: CHANGE_ME
        MYSQL_DATABASE: shop_app
        MYSQL_USER: shop_app
        MYSQL_PASSWORD: CHANGE_ME
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ../../images/apps/php-ci/testing:/docker-entrypoint-initdb.d
      cap_add:
        - SYS_NICE

  shop-app-nginx:
      build: ../../images/apps/nginx-php
      ports:
        - "1001:80"
        - "1111:443"
      container_name: shop-app-nginx
      command: nginx -g "daemon off;"
      volumes:
        - /path/to/app:/app
        - /etc/localtime:/etc/localtime:ro
      links:
        - shop-app-php1
        - shop-app-php2
        - shop-app-php3
      restart: always

  shop-app-migration:
      build: ../../images/apps/php-fpm
      container_name: shop-app-migration
      working_dir: /app
      volumes:
        - /path/to/app:/app
        - ../../images/apps/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        - ../../images/apps/php-fpm/migrate.sh:/migrate.sh
        - /etc/localtime:/etc/localtime:ro
      links:
        - shop-app-mysql
      command: /bin/bash -c "chmod +x /migrate.sh; /migrate.sh; "
      env_file:
        - shop-app.env.example

  shop-app-php1:
      build: ../../images/apps/php-fpm
      working_dir: /app
      container_name: shop-app-php1
      volumes:
        - /path/to/app:/app
        - ../../images/apps/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        - /etc/localtime:/etc/localtime:ro
        - /etc/ca-certificates.conf:/etc/ca-certificates.conf
      links:
        - shop-app-mysql
        - shop-app-memcached
        - shop-app-memcached1
        - shop-app-memcached2
      env_file:
        - shop-app.env.example
      restart: always

  shop-app-php2:
      build: ../../images/apps/php-fpm
      working_dir: /app
      container_name: shop-app-php2
      volumes:
        - /path/to/app:/app
        - ../../images/apps/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        - /etc/localtime:/etc/localtime:ro
        - /etc/ca-certificates.conf:/etc/ca-certificates.conf
      links:
        - shop-app-mysql
        - shop-app-memcached
        - shop-app-memcached1
        - shop-app-memcached2
      env_file:
        - shop-app.env.example
      restart: always

  shop-app-php3:
      build: ../../images/apps/php-fpm
      working_dir: /app
      container_name: shop-app-php3
      volumes:
        - /path/to/app:/app
        - ../../images/apps/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        - /etc/localtime:/etc/localtime:ro
        - /etc/ca-certificates.conf:/etc/ca-certificates.conf
      links:
        - shop-app-mysql
        - shop-app-memcached
        - shop-app-memcached1
        - shop-app-memcached2
      env_file:
        - shop-app.env.example
      restart: always

  shop-app-composer:
      build: ../../images/apps/composer
      container_name: shop-app-composer
      working_dir: /app
      volumes:
        - /path/to/app:/app
      # environment:
      #   - COMPOSER_MEMORY_LIMIT=-1
      # deploy:
      #   resources:
      #     limits:
      #       cpus: '0.50'
      #       memory: 2024M

  shop-app-node:
      build: ../../images/apps/node-vite
      container_name: shop-app-node
      working_dir: /app
      volumes:
        - /path/to/app:/app

  shop-app-memcached:
      image: memcached
      container_name: shop-app-memcached
      restart: always

  shop-app-memcached1:
      image: memcached
      container_name: shop-app-memcached1
      restart: always

  shop-app-memcached2:
      image: memcached
      container_name: shop-app-memcached2
      restart: always

  shop-app-worker:
      build: ../../images/apps/php-fpm
      working_dir: /app
      container_name: shop-app-worker
      volumes:
        - /path/to/app:/app
        - ../../images/apps/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        - /etc/localtime:/etc/localtime:ro
      links:
        - shop-app-mysql
      env_file:
        - shop-app.env.example
      restart: always
      command: /bin/bash -c "php artisan queue:work database --queue=shop-app"

  shop-app-cron:
      build: ../../images/apps/php-fpm
      working_dir: /app
      container_name: shop-app-cron
      restart: "always"
      links:
        - shop-app-mysql
        - shop-app-memcached
        - shop-app-memcached1
        - shop-app-memcached2
      env_file:
        - shop-app.env.example
      volumes:
        - /path/to/app:/app
        - ../../images/apps/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        - /etc/localtime:/etc/localtime:ro
      command: /bin/bash /app/.docker/images/php/cron.sh
