apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "console.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "console.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "console.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "console.fullname" . }}-sa
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: console
          image: "{{ .Values.werf.image.console }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
            - containerPort: 9433
              name: https
              protocol: TCP
          args:
            - server
          env:
            - name: CONSOLE_OPERATOR_MODE
              value: "on"
            {{- with .Values.env }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initcontainers }}
      initContainers:
      {{- toYaml . | nindent 8 }}
  {{- end}}
