{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecrets.serviceAccount.name }}
  namespace: {{ include "vault.namespace" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
{{- end }}
