{{- if and .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-secret
  labels: {{ include "labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    strategy.spinnaker.io/versioned: "false"
type: Opaque
data: {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}