apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: policy-gateway-vault-secrets
  namespace: estate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: policy-gateway-vault-secrets
    creationPolicy: Owner
  data:
  - secretKey: kafkaClientPassword
    remoteRef:
      key: secret/estate-kafka
      property: kafkaClientPassword
  - secretKey: file-storage.s3.accessKey
    remoteRef:
      key: secret/policy-gateway-app
      property: file-storage.s3.accessKey
  - secretKey: file-storage.s3.secretKey
    remoteRef:
      key: secret/policy-gateway-app
      property: file-storage.s3.secretKey
  - secretKey: treasury.policy-gateway.dgtry.pin
    remoteRef:
      key: secret/policy-gateway-app
      property: treasury.policy-gateway.dgtry.pin
  - secretKey: EXTERNAL_CSP_LICENSE
    remoteRef:
      key: secret/policy-gateway-app
      property: EXTERNAL_CSP_LICENSE
