{{- $app_urls := pluck .Values.global.cluster .Values.app.app_urls | first }}
{{- $app_url := pluck .Values.werf.env $app_urls | first | default $app_urls._default | first }}
{{- $app_url := printf "https://%s" (include "fl.value" (list $ . $app_url.host)) }}
{{- $name := $.Chart.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-worker
  labels:
    app: {{ $name }}-worker
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}-worker
  template:
    metadata:
      annotations:
        checksum/envs: {{ include (print $.Template.BasePath "/15-envs.yaml") . | sha256sum }}
        checksum/appurl: {{ $app_url | sha256sum }}
      labels:
        app: {{ $name }}-worker
        part-of: {{ $.Chart.Name }}-worker
    spec:
      {{ include "priorityClassName" . | indent 6 }}
      {{ include "affinity" . | nindent 6 }}
      {{ include "tolerations" . | nindent 6 }}
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: php
        image: {{ index .Values.werf.image "app" }}
        command: ["/usr/bin/php8.1"]
        workingDir: /app
        args: ["/app/artisan", "queue:work"]
        lifecycle:
          preStop:
            exec:
              command: ["/usr/bin/php8.1", "/app/artisan", "queue:restart"]
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
{{- include "resources_worker" $ | indent 8}}
        env:
        - name: APP_URL
          value: {{ $app_url | quote }}
        envFrom:
          - configMapRef:
              name: {{ $.Chart.Name }}-env
          - secretRef:
              name: {{ $.Chart.Name }}-env

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ $name }}-worker
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ $name }}-worker
  updatePolicy:
    updateMode: "Off"

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}-worker
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ $name }}-worker
