---
db_config_file: /etc/mysql/my.cnf
db_config_include_dir: /etc/mysql/conf.d
db_socket: /var/run/mysqld/mysqld.sock

db_service_name: mysql

db_version: '10.3'

db_apt_mirror: 'http://nyc2.mirrors.digitalocean.com'
db_apt_repositories:
  - 'deb [arch=amd64,i386,ppc64el] {{ db_apt_mirror }}/mariadb/repo/{{ db_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main'
  - 'deb-src {{ db_apt_mirror }}/mariadb/repo/{{ db_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main'

db_apt_keyserver: 'keyserver.ubuntu.com'
db_apt_keyid: 'F1656F24C74CD1D8'

db_pip_dependencies:
  - mysqlclient

db_apt_dependencies:
  - software-properties-common
  - build-essential
  - python3-mysqldb
  - python3-pip

db_apt_packages:
  - mariadb-server
  - mariadb-client

db_apt_tools_packages:
  - mysqltuner
  - percona-toolkit