---
- name: Run all_identityplatform
  hosts: swarm_manager
  gather_facts: true

  roles:
    - role: network
      tags: ["network"]

  tasks:

    - name: Deploy redis
      ansible.builtin.include_role:
        name: redis
      when:
        - "{{ (ig_caching_provider | string | lower) == 'redis' }}"
      ### Вызов роли для деплоя IG
    - name: Deploy ig
      ansible.builtin.include_role:
        name: ig
    ### Вызов роли для деплоя IgExt
    - name: Deploy IG EXT
      ansible.builtin.include_role:
        name: igext
      when:
        - "{{ ig_enable_ReverseAccess | bool }}"

    - block:
    ### Вызов роли для деплоя postgres
      - name: Include a role postgres
        ansible.builtin.include_role:
          name: idplat_postgres
        when:
          - "{{ idplat_postgres_install | bool }}"
          - "{{ not deploy_to_k8s | default(false) | bool }}"

      ### Ожидание выполенных 
      - name: Wait for service {{ docker_stack_name }}_idplat_postgres to reach running or failed state
        command: "docker service ps {{ docker_stack_name }}_idplat_postgres --format '{{ '{{.CurrentState}}' }}'"
        register: service_state
        until: "'Running' in service_state.stdout or 'Failed' in service_state.stdout"
        retries: 30
        delay: 10
        changed_when: false
        when:
          - "{{ idplat_postgres_install | bool }}"
          - "{{ not deploy_to_k8s | default(false) | bool }}"
        
      ### Вывод сообщение об ошибке и остановка Deploy
      - name: Error message
        fail:
          msg: "Состояние сервиса не 'Running'. Проверь лог"
        when:
          - "'Running' not in service_state.stdout"
          - "{{ idplat_postgres_install | bool }}"
          - "{{ not deploy_to_k8s | default(false) | bool }}"
      tags: idplat_postgres


    - block:
      ### Вызов роли для деплоя AM в docker без первоначальной настройки
      - name: Include a role am no first_deploy
        ansible.builtin.include_role:
          name: am
        when:
          - "{{ not am_first_deploy | bool }}"
          - "{{ not am_update_plugins | bool }}"
          - "{{ not am_update_migrations | bool }}"

      - block:
        ### Вызов роли для деплоя в docker с первоначальной настройки
        - name: Include a role am with first_deploy
          ansible.builtin.include_role:
            name: amcli
          when:
            - "{{ am_first_deploy | bool }} or {{ am_update_plugins | bool }} or {{ am_update_migrations | bool }}"

        ### Ожидание выполенныя первоначальных настроек
        - name: Wait for service {{ docker_stack_name }}_{{ amcli_name }} to reach complete or failed state
          command: "docker service ps {{ docker_stack_name }}_{{ amcli_name }} --format '{{ '{{.CurrentState}}' }}'"
          register: service_state
          until: "'Complete' in service_state.stdout or 'Failed' in service_state.stdout"
          retries: 30
          delay: 10
          changed_when: false
          when:
            - "{{ am_first_deploy | bool }} or {{ am_update_plugins | bool }} or {{ am_update_migrations | bool }}"
          
        ### Вывод сообщение об ошибке и остановка Deploy
        - name: Error message
          fail:
            msg: "First deploy no Complete !"
          when:
            - "'Complete' not in service_state.stdout"
            - "{{ am_first_deploy | bool }} or {{ am_update_plugins | bool }} or {{ am_update_migrations | bool }}"

        ### Удаление контейнера первоначальных настроек в docker после успешного выполнения (не удаляет при включенном debug)
        - name: "{{ amcli_name }} -> Docker service {{ docker_stack_name }}_{{ amcli_name }} remove"
          docker_swarm_service:
            name: "{{ docker_stack_name }}_{{ amcli_name }}"
            state: absent
          when: 
            - "{{ am_first_deploy | bool }} or {{ am_update_plugins | bool }} or {{ am_update_migrations | bool }}"
            - "'Complete' in service_state.stdout"
            - "{{ not am_deploy_debug | bool }}"

        ### Запуск сервиса после успешного выполнения первоначальных настроек
        - name: Check if the first deploy was successful and run the second playbook
          ansible.builtin.include_role:
            name: am
          vars:
            am_name: "am"
          when: 
            - "'Complete' in service_state.stdout"
            - "{{ am_first_deploy | bool }} or {{ am_update_plugins | bool }} or {{ am_update_migrations | bool }}"

        when:
          - "{{ am_first_deploy | bool }} or {{ am_update_plugins | bool }} or {{ am_update_migrations | bool }}"
      tags: am

