{{- if .Values.env -}}
kind: Secret
apiVersion: v1
metadata:
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  name: {{ include "base-chart.fullname" . }}-env
  labels:
    {{- include "base-chart.labels" . | nindent 4 }}
data:
  {{- template "envify" (list "" .Values.global.env ) }}
  {{- template "envify" (list "" .Values.env ) }}
type: Opaque
{{- end }}