kind: Secret
apiVersion: v1
metadata:
  name: {{ include "front-base.fullname" . }}-env
  labels:
    {{- include "front-base.labels" . | nindent 4 }}
data:
  {{- if .Values.globalInherit }}
  {{- template "envify" (list "" .Values.global.env ) }}
  {{- end }}
  {{- template "envify" (list "" .Values.env ) }}
type: Opaque
