---
- name: create users
  become: true
  user:
    name: "{{ item }}"
    state: present
    groups: "{{ user_groups }}"
    password: "{{ lookup('file', '../files/' + item + '.password') }}"
    shell: /bin/bash
  loop: "{{ users }}"

- name: set authorized_keys
  become: true
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '../files/' + item + '.pub') }}"
  loop: "{{ users }}"
