apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openobserve-collector.fullname" . }}
  labels:
    {{- include "openobserve-collector.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/status
      - namespaces
      - nodes
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
