---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
type: Opaque
data:
  .restic: {{ .Values.ssh_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: buckets-{{ .Values.werf.env }}
type: Opaque
stringData:
  buckets.yaml: |
{{ toYaml (pluck .Values.werf.env .Values.buckets |  first | default .Values.buckets._default) | indent 4 }}