apiVersion: v2
name: cryptopro
description: Thin CryptoPro CSP volume umbrella. One cprocsp PVC with lookup + keep, no bootstrap.
type: application
version: 0.1.0
appVersion: "0.0.2"

dependencies:
  - name: base-chart
    version: 0.2.1
    repository: "file://../_libs/base-chart"
    alias: application
    condition: application.enabled
