user www-data;
worker_processes auto;
pid /run/nginx.pid;

load_module modules/ngx_stream_module.so;

events {
	worker_connections 768;
}

stream {
  upstream tcp_np {
    server 10.10.10.12:3306;
  }

  log_format basic '$remote_addr [$time_local] '
                 '$protocol $status $bytes_sent $bytes_received '
                 '$session_time';
  server {
    listen 0.0.0.0:3307;
    access_log /var/log/nginx/np-access.log basic buffer=32k;
    proxy_pass tcp_np;
  }

}

