replicaCount: 1
nodeport: 32015
env:
  KC_DB_URL: jdbc:postgresql://10.10.0.11:5432/shop_keycloak_test2?sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory
  KC_DB_USERNAME: shop_keycloak_test2
  KC_DB_PASSWORD: CHANGE_ME
  KC_DB_SCHEMA: public 
  KC_FEATURES: preview
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: CHANGE_ME
  KC_CACHE: local
resources:
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 3Gi
